# Generated by Django 5.0 on 2023-12-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_recipe_difficulty_alter_recipe_nbrcalories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='Client',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='step',
            old_name='descreption',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='imageUrl',
            field=models.ImageField(blank=True, null=True, upload_to='recipe_images'),
        ),
    ]
